Wait for client socket to appear
logstash-plugins/logstash-input-unix pull request #19
Opened 2017-01-23 12:50 UTC by breml

More resilent in case of errors (handle error conditions).

For best effect, merge together with #18.

2017-01-24 10:08 UTC, breml commented
From what I can tell, the failing travis build was not because of my change but due to a dependency problem.

2017-02-11 00:47 UTC, suyograo requested changes

2017-02-11 00:47 UTC, suyograo commented on lib/logstash/inputs/unix.rb
> +          @logger.debug("Opened connection 1", :client => @path)
What does connection 1 mean here?

2017-02-11 00:47 UTC, suyograo commented on lib/logstash/inputs/unix.rb
> +          sleep(5)
Can you make this configurable?

2017-02-13 07:57 UTC, breml commented on lib/logstash/inputs/unix.rb
> +          @logger.debug("Opened connection 1", :client => @path)
this is a typo, cleaned it up

2017-02-13 07:57 UTC, breml commented on lib/logstash/inputs/unix.rb
> +          sleep(5)
made it configurable

2017-02-13 08:03 UTC, breml commented
@suyograo resolved the requested changes.

2017-02-14 08:14 UTC, merged